### ISSUE TITLE
Prometheus Pushgateway

### ISSUE THREAD

**Issue by krisavi** [chrissnell/crabby#8]
It seems Prometheus is not working at all.

First, the prometheus does not accept . as label separator.
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
Accepts regex `[a-zA-Z_:][a-zA-Z0-9_:]*`
Second issue seems to be "duplicate metrics collector registration attempted"

**Comment by chrissnell** [comment]
The pushgateway support has been replaced by an actual Prometheus endpoint.  This label naming bug has been fixed, too.  Check it out!

There is a `config-simple.yaml` file in the examples to get you going.
